# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Test
on:
  push: {}

  workflow_dispatch:
    inputs:
      optioan_boolean_in:
        description: "optional boolean"
        required: false
        type: boolean
      required_boolean_in:
        description: "required boolean"
        required: true
        type: boolean
        default: true
      number_in:
        description: "number input"
        type: number
        default: 42
      string_in:
        description: "string input"
        type: string
        default: "foo bar"
      environment_in:
        description: "environment input"
        type: environment
        required: false
      log_level:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

#concurrency:
#  group: single-group
#  cancel-in-progress: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
# https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

jobs:
  first_job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: hello-step
        run: |
          echo hello
          sleep 15

  second_job:
    name: Second job
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: hello-step
        run: |
          echo hello
          sleep 20

  build_job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: hello-step
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          LOG_LEVEL: ${{ inputs.log_level }}
        run: |
          echo hello
          echo $LOG_LEVEL
          echo "::debug::Log Level $LOG_LEVEL"
          echo "::notice file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo "::warning file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo "::error file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo $EVENT_CONTEXT
          echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: done
        env:
          SELECTED_COLOR: ${{ steps.hello-step.outputs.SELECTED_COLOR }}
        run: |
          echo "The selected color is $SELECTED_COLOR"
          echo "Built at $BUILD_TIME"
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo '`code line`' >> $GITHUB_STEP_SUMMARY
          printf '```\ncode block\ncode block\n```\n' >> $GITHUB_STEP_SUMMARY
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
          retention-days: 1
          compression-level: 0
