# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Test
on:
  push: {}

  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions

jobs:
  build_job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: hello
        id: hello-step
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          LOG_LEVEL: ${{ inputs.log_level }}
        run: |
          echo hello
          echo $LOG_LEVEL
          echo "::debug::Log Level $LOG_LEVEL"
          echo "::notice file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo "::warning file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo "::error file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo $EVENT_CONTEXT
          echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: done
        env:
          SELECTED_COLOR: ${{ steps.hello-step.outputs.SELECTED_COLOR }}
        run: |
          echo "The selected color is $SELECTED_COLOR"
          echo "Built at $BUILD_TIME"
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

