# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Test
on:
  push: {}

  workflow_dispatch:
    inputs:
      optioan_boolean_in:
        description: "optional boolean"
        required: false
        type: boolean
      required_boolean_in:
        description: "required boolean"
        required: true
        type: boolean
        default: true
      number_in:
        description: "number input"
        type: number
        default: 42
      string_in:
        description: "string input"
        type: string
        default: "foo bar"
      environment_in:
        description: "environment input"
        type: environment
        required: false
      log_level:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

concurrency:
  group: single-group
  cancel-in-progress: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
# https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

jobs:
  do_work:
    name: Do Work ${{ matrix.name }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        name: [test]
        input_flag: [false, true]
        input_value: [null]
        include:
          - name: xxx
            input_flag: true
            input_value: 12
    uses: ./.github/workflows/work.yaml
    with:
      input_flag: ${{ matrix.input_flag }}
      input_value: ${{ matrix.input_value || 11 }}

  test_matrix:
    name: Test Matrix
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        first: [1, 2, 3, 4, 5]
        second: [10, 20, 30, 40, 50]
    if: "${{ false }}"
    steps:
      - name: Matrix ${{ matrix.first }}, ${{ matrix.second }}
        run: |
          sleep 5

  first_job:
    name: First job
    runs-on: ubuntu-latest
    concurrency:
      group: main
    if: "${{ false }}"
    steps:
      - name: hello
        id: hello-step
        run: |
          echo "first start" >> $GITHUB_STEP_SUMMARY
          sleep 15
          echo "first finish" >> $GITHUB_STEP_SUMMARY

  second_job:
    name: Second job
    runs-on: ubuntu-latest
    concurrency:
      group: main
    if: "${{ false }}"
    steps:
      - name: hello
        id: hello-step
        run: |
          echo "second start" >> $GITHUB_STEP_SUMMARY
          sleep 20
          echo "second finish" >> $GITHUB_STEP_SUMMARY

  third_job:
    name: Third job
    runs-on: ubuntu-latest
    concurrency:
      group: main
    if: "${{ false }}"
    steps:
      - name: hello
        id: hello-step
        run: |
          echo "third start" >> $GITHUB_STEP_SUMMARY
          sleep 30
          echo "third finish" >> $GITHUB_STEP_SUMMARY

  build_job:
    name: Build Job
    runs-on: ubuntu-latest
    if: "${{ false }}"
    steps:
      - name: hello
        id: hello-step
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          LOG_LEVEL: ${{ inputs.log_level }}
        run: |
          echo hello
          echo $LOG_LEVEL
          echo "::debug::Log Level $LOG_LEVEL"
          echo "::notice file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo "::warning file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo "::error file=.github/workflows/test.yaml,line=33,title=Notice Title $LOG_LEVEL::Log Level $LOG_LEVEL"
          echo $EVENT_CONTEXT
          echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: done
        env:
          SELECTED_COLOR: ${{ steps.hello-step.outputs.SELECTED_COLOR }}
        run: |
          echo "The selected color is $SELECTED_COLOR"
          echo "Built at $BUILD_TIME"
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo '`code line`' >> $GITHUB_STEP_SUMMARY
          printf '```\ncode block\ncode block\n```\n' >> $GITHUB_STEP_SUMMARY
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
          retention-days: 1
          compression-level: 0
