# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Test
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo hello
