name: Work

on:
  workflow_call:
    inputs:
      input_flag:
        description: Input flag
        type: boolean
        required: false
        default: false

  workflow_dispatch:
    inputs:
      input_flag:
        description: Input flag
        type: boolean
        required: false
        default: false

jobs:
  do_job:
    runs-on: ubuntu-latest
    steps:
      - name: do_step
        run: |
          echo "Flag: ${{ inputs. }}"
