name: Work

on:
  workflow_call:
    inputs:
      input_flag:
        description: Input flag
        type: boolean
        required: false
        default: false
      input_value:
        description: Input value
        type: number
        required: false
        default: 42

  workflow_dispatch:
    inputs:
      input_flag:
        description: Input flag
        type: boolean
        required: false
        default: false
      input_value:
        description: Input value
        type: number
        required: false
        default: 42

jobs:
  do_job:
    runs-on: ubuntu-latest
    steps:
      - name: do_step
        run: |
          echo "Flag: ${{ inputs.input_flag }}"
          echo "Value: ${{ inputs.input_value }}"
